### PR TITLE
Clock divide example

### PR DESCRIPTION
**Pull request by icnagy**
Clock divide example based on Ardcore example (https://github.com/darwingrosse/ArdCore-Code/tree/master/20%20Objects/AC05_ClockDivide)

### CODE REVIEW

**Comment by thopa** [comment]
Thanks again! Im having trouble with the range of the potentiometers inside this sketches.Getting half of the value when having the shield plugged in . Actually im getting the clock being received on gateinA outputted on GateOutA, and pot is not doing anything so far. Have chequed with the shield and arduino plugged to the computer or to the Eurorack power.

**Comment by icnagy** [comment]
Thanks for testing it! (I can only do that later)
I think the second problem (Gate in repeated on gate out) probably means you got the potentiometers in the wrong pins... Oh man. I forgot that the A0 and A1 pins are used by the Synapse shield for CV in A and B!
Let me update the code. You'll have to use A2/A3 for the pot inputs.

**Comment by icnagy** [comment]
@thopa could you please test the updated version with the pots connected to A2,A3 and A4? (A2,A3 are the 2 dividers (0-32) and A4 is the division offset input (0-16))

**Comment by thopa** [comment]
Hi thanks for your reply. 
Im have tried the latest sketch, and connected to the ports as indicated and now i get the same clock as on the input, or if i move the pot no clock at all.
Tried with different potentiometers and same bug. Im going to change boards.
Ok so I changed boards and tested the potentiometer readings with synapse and a 
  Serial.println("analog 2 is: ");
  Serial.println( val);
  delay(250);
I get readings but no divisions, its either on or off. Many thanks

**Comment by icnagy** [comment]
@thopa I got this one working on my setup. The pot values were scaled wrong that has been fixed as well. I can get the pots to run between 1 and 32 and the gate out is divided accordingly. Let me know how you get along with it!

**Comment by icnagy** [comment]
@shaduzlabs I hope these won't cause copyright issues. Let me know if you're not happy with these samples. Thanks!

**Comment by shaduzlabs** [comment]
@icnagy thanks for your contribution, the original code which is linked in the header of the source file that you added is licensed under a Creative Commons (CC BY-NC) license, so it should be fine.

**Pull request merged**
